#!/bin/bash

#PBS -N PanelApp_Panel_Summariser 
#PBS -r n
#PBS -l walltime=2:00:00
#PBS -l ncpus=2,mem=10Gb
#PBS -m ae
#PBS -M Alan.Robertson@qimrberghofer.edu.au 
#PBS -o /mnt/backedup/home/alanR/experiments/log/panelapp
#PBS -e /mnt/backedup/home/alanR/experiments/log/panelapp

#-------------------------------------
# 
# Script:	1-3 Download PanelApp IDs 
# Summary:	This script was designed to run a python script that summarises all the different versions of a panel into monthly summaries 
# Created: 	2023-05-03
# 
#-------------------------------------

#-------------------------------------------
# ENTER YOUR DEETS
#------------------------------------------

#Name experiment
NAME="PANELAPP PANEL SUMMARIZER" 
#Define vars
SCRIPT="1-3_PanelSummariser.py"
RAW_LOC="/mnt/backedup/home/alanR/ALAN_SCRIPTS/2023/PROD/1-3"
#Define parameters file
PARAM="1-3_summarise_params.txt"

echo "Experiment name: ${NAME}"  
echo "Parameter file: ${PARAM}"
echo ""

#Extract the version of PanelApp being used from the params file 
VERSION=$(less ${RAW_LOC}/${PARAM} | awk '/VER/ {print $2}')
OUT_DIR=$(less ${RAW_LOC}/${PARAM} | awk '/OUTPUTDIR/ {print $2}')
echo "Version = ${VERSION}"
echo "OUT-DIR = ${OUT_DIR}"
echo""

#save additional information with logs
LOG_DIR="/mnt/backedup/home/alanR/experiments/log/panelapp"
timestamp=$(date "+%Y-%m-%d_%H-%M")
cp ${RAW_LOC}/${PARAM} ${LOG_DIR}/${timestamp}_1-3_${PARAM}

#Load Modules
module load python/3.9.13 
echo "Modules loaded:"
module list
echo ""

#Define proxy (ensure cluster can connect to websites outside of QIMR)
#source ~/.proxy

#Define the  working directory
OUTPUT_DIR=${OUT_DIR}
mkdir -p ${OUTPUT_DIR}
echo "Moving to:"
cd ${OUTPUT_DIR}
pwd
#sleep 5

#-------------------------------------------
# Part 2: Running the tool 
#------------------------------------------
echo "PRODUCING MONTHLY SUMMARIES FOR PANELAPP ${VERSION}"
#echo "DOWNLOADING THE PANELS LISTED IN: ${ID_FILE}"
python3  ${RAW_LOC}/${SCRIPT} --file-path ${RAW_LOC}/${PARAM} 
#echo ""

#echo "Files Produced:"
#ls
